{--
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
--}

fibonacci :: Int -> Int
fibonacci n = fibTR n 0 1
            where
              fibTR 0 a2  _ = a2
              fibTR 1 _  a1 = a1
              fibTR b a2 a1 =  fibTR (b - 1) a1 (a1 + a2)

allFibs = [ fibonacci x | x <- [1..]]
evenFibs = [ x | x <- allFibs, even x ]
candidateFibs = takeWhile (< 4000000) evenFibs

main = do
  putStrLn $ show (sum candidateFibs)
